version: '3'
services:
  web:
    build: ./web
    ports:
      - 8080:8080
    volumes:
      - ./settings:/settings
      - ./jenkins:/var/lib/jenkins
      - ./log/jenkins:/var/log/jenkins
    networks:
      app_net:
        ipv4_address: 172.16.254.3
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.254.0/24
