version: '3'
services:
  web:
    build: ./web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    links:
      - "db"
    networks:
      app_net:
        ipv4_address: 172.16.254.3
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "33306:3306"
    volumes:
      - "./mysql/db:/var/lib/mysql" # ホストのディレクトリにDBのデータを保持するようにしている
      - "./mysql/logs/mysql:/var/log/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    # utf-8でDBを初期化
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci"
    networks:
      app_net:
        ipv4_address: 172.16.254.2
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.254.0/24
